"""add private generated artifacts

Revision ID: 20260727_04
Revises: 20260727_03
Create Date: 2026-07-27
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260727_04"
down_revision: Union[str, Sequence[str], None] = "20260727_03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create private export metadata while generated bytes remain on a Docker volume."""
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("agent_run_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.UniqueConstraint("user_id", "source_type", "source_id", "format", name="uq_artifact_source_format"),
    )
    op.create_index("ix_artifacts_user_id", "artifacts", ["user_id"])
    op.create_index("idx_artifacts_owner_source", "artifacts", ["user_id", "source_type", "source_id"])
    op.create_index("idx_artifacts_owner_run", "artifacts", ["user_id", "agent_run_id"])


def downgrade() -> None:
    """Drop private export metadata but leave volume files for operator-managed cleanup."""
    op.drop_index("idx_artifacts_owner_run", table_name="artifacts")
    op.drop_index("idx_artifacts_owner_source", table_name="artifacts")
    op.drop_index("ix_artifacts_user_id", table_name="artifacts")
    op.drop_table("artifacts")
